# Generated by Django 4.0.5 on 2022-06-21 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relojcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Ingreso'),
        ),
    ]
