# Generated by Django 4.0.5 on 2022-06-26 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relojcontrol', '0002_entrada_entrada_alter_entrada_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHorario', models.CharField(max_length=100, verbose_name='Horario')),
                ('lunesE', models.TimeField(verbose_name='Lunes Entrada')),
                ('lunesS', models.TimeField(verbose_name='Lunes Salida')),
                ('martesE', models.TimeField(verbose_name='Martes Entrada')),
                ('martesS', models.TimeField(verbose_name='Martes Salida')),
                ('MiercolesE', models.TimeField(verbose_name='Miercoles Entrada')),
                ('MiercolesS', models.TimeField(verbose_name='Miercoles Salida')),
                ('JuevesE', models.TimeField(verbose_name='Jueves Entrada')),
                ('JuevesS', models.TimeField(verbose_name='Jueves Salida')),
                ('ViernesE', models.TimeField(verbose_name='Viernes Entrada')),
                ('ViernesS', models.TimeField(verbose_name='Viernes Salida')),
            ],
        ),
        migrations.AlterField(
            model_name='entrada',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(default='Ingreso', editable=False, max_length=8, verbose_name=''),
        ),
    ]
