# Generated by Django 4.0.5 on 2022-07-01 11:32

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relojcontrol', '0003_horario_alter_entrada_entrada_alter_entrada_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Entrada', editable=False, max_length=500)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='JuevesE',
            new_name='juevesE',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='JuevesS',
            new_name='juevesS',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='MiercolesE',
            new_name='miercolesE',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='MiercolesS',
            new_name='miercolesS',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='ViernesE',
            new_name='viernesE',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='ViernesS',
            new_name='viernesS',
        ),
    ]
