# Generated by Django 4.0.5 on 2022-07-01 14:45

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relojcontrol', '0004_control_delete_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Salida', editable=False, max_length=500)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
